<?php

return [
    'board' => [
        [
            'name' => 'Hugo Clarke-Wing',
            'title' => 'Président',
            'promotion' => 'EPL/S 2015',
            'job' => 'OPL Transavia France',
            'linkedin' => 'https://www.linkedin.com/in/mrhugo',
            'bio' => 'Après un premier mandat au Bureau de l’AGEPAC entre 2019 et 2020 en tant que Secrétaire Général, Hugo est élu Président en 2020. Il est incapable de sourire les yeux ouverts.',
        ],
        [
            'name' => 'Hugo Bao',
            'title' => 'Vice-Président',
            'promotion' => 'CP ATPL 2019',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/hugo-bao-ba121418a/',
            'bio' => 'Investi dans le bénévolat depuis son arrivée à l’ENAC, Hugo accède au poste de Vice-Président en 2022. Il est chargé d’assister le Président.',
        ],
        [
            'name' => 'Adrián Lucq-Bibiloni',
            'title' => 'Secrétaire Général',
            'promotion' => 'EPL/U 2018',
            'job' => 'Chef de Division Gestion de Production ENAC',
            'linkedin' => 'https://www.linkedin.com/in/adrian-lucq/',
            'bio' => 'Maître de l’efficacité, depuis le début de son mandat en 2020 Adrián a su trouver le parfait équilibre entre rédaction de comptes-rendus et pause piscine.',
        ],
        [
            'name' => 'Pierre Grézaud',
            'title' => 'Secrétaire Général adjoint',
            'promotion' => 'EPL/U 2021',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Nouvellement élu secrétaire adjoint, Pierre va tenter de suivre le rythme d’Adrián, car si il est au moins aussi performant dans les pauses piscines, l’art des comptes-rendus s’acquiert avec le temps.',
        ],
        [
            'name' => 'Aurélien Couturier',
            'title' => 'Trésorier',
            'promotion' => 'EPL/S 2019',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Même occuper le poste de trésorier après la crise du COVID ne fait pas peur à Aurélien. Avec lui les membres sont satisfaits ET remboursés.',
        ],
        [
            'name' => 'Marek Mádl',
            'title' => 'Responsable Communication',
            'promotion' => 'CP ATPL 2015',
            'job' => 'OPL Transavia France',
            'linkedin' => 'https://www.linkedin.com/in/marekmadl/',
            'bio' => 'Expert en instruction à la tchèque et en SOP’s polonaises, Marek cache également d’autres talents. Il a su raviver les couleurs de l’AGEPAC à l’aide de ses vidéos d’aviation.',
        ],
        [
            'name' => 'Julien Thomasson',
            'title' => 'Responsable Emploi et Réseau',
            'promotion' => 'EPL/U 2019',
            'job' => 'OPL Ryanair',
            'linkedin' => 'https://www.linkedin.com/in/julien-thomasson-876314133/',
            'bio' => 'Mordu d’aviation, Julien travaille depuis 2020 à établir des partenariats avec des compagnies partenaires. Si vous souhaitez travailler avec des EPL il sera votre interlocuteur privilégié!',
        ],
        [
            'name' => 'Tom Guedj',
            'title' => 'Responsable adjoint Emploi et Réseau',
            'promotion' => 'EPL/S 2019',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/tom-g-06b8a0123/',
            'bio' => 'Poussé par l’envie de transmettre sa passion, Tom a dès le début de sa formation EPL dispensé des cours BIA. Depuis 2021, il seconde Julien au pôle Emploi et Réseau.',
        ],
        [
            'name' => 'Paul Viviant',
            'title' => 'Responsable Formation',
            'promotion' => 'EPL/S 2015',
            'job' => 'OPL Transavia France',
            'linkedin' => '',
            'bio' => 'Toujours investi dans l’éducation, Paul consacre le peu de temps libre qui lui reste en dehors de son agrégation de mathématiques au suivi de la formation des EPL.',
        ],
        [
            'name' => 'Théophile Pellissier',
            'title' => 'Liaison Partenaires Industriels',
            'promotion' => 'EPL/S 2017',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/théophile-pellissier/',
            'bio' => 'Tombé dans la marmite de l’aviation dès sa naissance, Théophile est lobbyist en herbe, et il s’occupe des relations avec nos partenaires depuis 2020.',
        ],
        [
            'name' => 'Thomas Salacroux',
            'title' => 'Liaison adjoint Partenaires Industriels',
            'promotion' => 'EPL/U 2021',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/thomas-salacroux-b28487141/',
            'bio' => 'Allant du planeur, à l’aéroclub, à l’ATPL théorique, à l’ENAC, il semblait évident que Thomas allait rejoindre le Bureau tôt ou tard. Avec Théophile, il manie l’art du dialogue avec nos partenaires.',
        ],
        [
            'name' => 'Morgane Maillet',
            'title' => 'Responsable Événements',
            'promotion' => 'EPL/S 2018',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/morgane-maillet-309541180/',
            'bio' => 'Longtemps impliquée dans l’associatif, Morgane a rejoint le bureau de l’AGEPAC en 2020. Depuis, elle concocte des évènements aux petits oignons pour EPLs, petits et grands.',
        ],
    ],

    'council' => [
        [
            'name' => 'César Chroscik',
            'title' => 'Responsable Promotions EPL/S 2010 & antérieures',
        ],
        [
            'name' => 'Julian Krummel',
            'title' => 'Responsable Promotion EPL/S 2011',
        ],
        [
            'name' => 'Jacques Preiss',
            'title' => 'Responsable Promotion EPL/S 2012',
        ],
        [
            'name' => 'Erwan Marlier',
            'title' => 'Responsable Promotion EPL/S 2013',
        ],
        [
            'name' => 'Timothée Barry',
            'title' => 'Responsable Promotion EPL/S 2014',
        ],
        [
            'name' => 'Théo Chamiot-Prieur',
            'title' => 'Responsable Promotion EPL/S 2015',
        ],
        [
            'name' => 'Thomas Izarn',
            'title' => 'Responsable Promotion EPL/S 2016',
        ],
        [
            'name' => 'Victor Agopian',
            'title' => 'Responsable Promotion EPL/S 2017',
        ],
        [
            'name' => 'Lilian Berquier',
            'title' => 'Responsable Promotion EPL/S 2018',
        ],
        [
            'name' => 'Louis Geig',
            'title' => 'Responsable Promotion EPL/S 2019',
        ],
        [
            'name' => 'Jonathan Ganter',
            'title' => 'Responsable Promotion EPL/S 2020'
        ],
        [
            'name' => 'Thomas Joffraud',
            'title' => 'Responsable Promotion EPL/S 2021'
        ],
        [
            'name' => 'Céline Rosier',
            'title' =>'Responsable Promotions EPL/U & EPL/P'
        ],
        [
            'name' => 'Victor Krogmann',
            'title' => 'Responsable Promotions Cursus Préparatoire ATPL',
        ],
        [
            'name' => 'Jérôme Walrave',
            'title' =>'Ancien Président 2002&#8209;2006',
        ],
        [
            'name' => 'Simon Spriet',
            'title' =>'Ancien Président 2006&#8209;2008',
        ],
        [
            'name' => 'Pierre Petaux',
            'title' =>'Ancien Président 2008&#8209;2010',
        ],
        [
            'name' => 'Timoté Dufour',
            'title' =>'Ancien Président 2010&#8209;2014',
        ],
        [
            'name' => 'Benjamin Payet',
            'title' =>'Ancien Président 2014&#8209;2016',
        ],
        [
            'name' => 'Damien Lacombe',
            'title' =>'Ancien Président 2016&#8209;2019',
        ],
        [
            'name' => 'Simon Louyot',
            'title' =>'Ancien Président 2019&#8209;2020',
        ],
    ],

    'employers_showcase' => [
        // 'Aegean Airlines',
        'Aerosotravia',
        // 'Air Austral',
        // 'Air Caraibes',
        // 'Air Corsica',
        // 'Air France Hop',
        'Air France',
        'Air Macau',
        // 'Air Mauritius',
        // 'airBaltic',
        // 'AirCalin',
        // 'ASL Airlines France',
        // 'ASL Airlines Switzerland',
        // 'Astonfly',
        // 'Austrian Airlines',
        // 'Babcock International',
        // 'Blue Islands',
        // 'British Airways',
        'Cargolux',
        'Cathay Pacific',
        // 'Cebu Pacific',
        // 'Chalair Aviation',
        // 'CityJet',
        // 'Cretan Eagle Aviation',
        // 'DHL',
        'easyJet',
        'Emirates',
        // 'ENAC',
        // 'Etihad Airways',
        // 'Etihad Regional',
        // 'Flybe',
        // 'Flydubai',
        // 'Garuda Indonesia',
        // 'GlobalJet',
        // 'GlobeAir',
        // 'Hong Kong Airlines',
        // 'Intercaribbean Airways',
        // 'Jetstar',
        // 'La Compagnie',
        // 'LOT Polish Airlines',
        // 'Lufthansa Cityline',
        'Luxair',
        // 'LuxAviation',
        // 'Norwegian',
        // 'Oyonnair',
        // 'PixAir Survey',
        // 'PrivatAir',
        // 'Qantas',
        // 'Qatar Airways',
        // 'Ryanair',
        // 'St Barth Commuter',
        // 'St Barth Executive',
        // 'Susi Air',
        // 'Swiss',
        'Transavia',
        // 'TUI Fly',
        // 'VallJet',
        'VistaJet',
        // 'Volotea',
        // 'Vueling',
        // 'West Atlantic',
        // 'Wizz Air',
    ],

    'fallen_epls' => [
        [
            'name' => 'Guillaume G.',
            'promotion' => 'EPL 2006',
            'death' => 'Octobre 2011',
        ],
        [
            'name' => 'Pierre H.',
            'promotion' => 'EPL 2008',
            'death' => 'Juillet 2011',
        ],
        [
            'name' => 'Nicolas B.',
            'promotion' => 'EPL 2008',
            'death' => 'Décembre 2009',
        ],
        [
            'name' => 'Céline S.',
            'promotion' => 'EPL 2004',
            'death' => 'Aout 2004',
        ],
        [
            'name' => 'Jean M.',
            'promotion' => 'EPL A12',
            'death' => 'Juillet 2000',
        ],
    ],
];
