<?php

return [
    'board' => [
        [
            'name' => 'Hugo Bao',
            'title' => 'Président',
            'promotion' => 'CP ATPL 2019',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/hugo-bao-ba121418a/',
            'bio' => 'Très investi dans le bénévolat depuis ses débuts à l’ENAC, Hugo commence un premier mandat au Bureau de l’AGEPAC en 2022 en tant que Vice-Président. Il est élu Président en 2023.',
        ],
        [
            'name' => 'Thomas Joffraud',
            'title' => 'Vice-Président',
            'promotion' => 'EPL/S 2021',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Empathique et travailleur, Thomas a rejoint l’équipe du Bureau afin de s’impliquer au développement de la communauté EPL ainsi qu’à sa cohésion par le biais de l’AGEPAC.',
        ],
        [
            'name' => 'Pierre Grézaud',
            'title' => 'Secrétaire Général',
            'promotion' => 'EPL/U 2021',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Nouvellement élu secrétaire adjoint, Pierre va tenter de suivre le rythme d’Adrián, car si il est au moins aussi performant dans les pauses piscines, l’art des comptes-rendus s’acquiert avec le temps.',
        ],
        [
            'name' => 'Céline Rosier',
            'title' => 'Secrétaire Général adjointe',
            'promotion' => 'EPL/U 2020',
            'job' => 'OPL Transavia France',
            'linkedin' => '',
            'bio' => 'Investie dans l’associatif depuis plusieurs années, Céline a à cœur de contribuer à l’activité de l’AGEPAC et à maintenir le lien intergénérationnel entre les EPL. Formant avec Pierre un duo de choc, elle veille au bon fonctionnement de l’association, toujours dans la bonne humeur et le partage !',
        ],
        [
            'name' => 'Aurélien Couturier',
            'title' => 'Trésorier',
            'promotion' => 'EPL/S 2019',
            'job' => 'OPL Transavia France',
            'linkedin' => '',
            'bio' => 'Même occuper le poste de trésorier après la crise du COVID ne fait pas peur à Aurélien. Avec lui les membres sont satisfaits ET remboursés.',
        ],
        [
            'name' => 'Raphaël Timmerman',
            'title' => 'Responsable Communication',
            'promotion' => 'EPL/S 2022',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Expert en moyens de communication d’une époque révolue, plus familier à l’aéropostale qu’à Instagram, Raphaël ne vous répondra que par VHF.',
        ],
        [
            'name' => 'Tom Guedj',
            'title' => 'Responsable Emploi et Réseau',
            'promotion' => 'EPL/S 2019',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/tom-g-06b8a0123/',
            'bio' => 'Poussé par l’envie de transmettre sa passion, Tom a dès le début de sa formation EPL dispensé des cours BIA. Depuis 2021, il est au pôle Emploi et Réseau.',
        ],
        [
            'name' => 'Victor Krogmann',
            'title' => 'Responsable adjoint Emploi et Réseau',
            'promotion' => 'CP ATPL 2020',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Passionné et investi depuis son jeune âge dans les aéroclubs qu’il a fréquenté, Victor n’a pas hésité à rejoindre l’équipe du Bureau en 2023. Il accompagne Tom au pôle Emploi et Réseau.',
        ],
        [
            'name' => 'Jonathan Ganter',
            'title' => 'Responsable Formation',
            'promotion' => 'EPL/S 2020',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Toujours volontaire pour apporter son aide à ses collègues, Jonathan s’est impliqué dans l’association dès son arrivée à l’ENAC pour représenter sa promotion au Conseil. Depuis 2023, il s’occupe de la formation des EPL.',
        ],
        [
            'name' => 'Thomas Salacroux',
            'title' => 'Liaison Partenaires Industriels',
            'promotion' => 'EPL/U 2021',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/thomas-salacroux-b28487141/',
            'bio' => 'Allant du planeur, à l’aéroclub, à l’ATPL théorique, à l’ENAC, il semblait évident que Thomas allait rejoindre le Bureau tôt ou tard. Il manie l’art du dialogue avec nos partenaires.',
        ],
        [
            'name' => 'Morgane Maillet',
            'title' => 'Responsable Événements',
            'promotion' => 'EPL/S 2018',
            'job' => '',
            'linkedin' => 'https://www.linkedin.com/in/morgane-maillet-309541180/',
            'bio' => 'Longtemps impliquée dans l’associatif, Morgane a rejoint le bureau de l’AGEPAC en 2020. Depuis, elle concocte des évènements aux petits oignons pour EPLs, petits et grands.',
        ],
        [
            'name' => 'Elisabeth Arnaud',
            'title' => 'Responsable Événements adjointe',
            'promotion' => 'EPL/U 2022',
            'job' => '',
            'linkedin' => '',
            'bio' => 'Après avoir participé à plusieurs événements, c’est assez naturellement qu’Elisabeth est venue à s’impliquer dans l’organisation à son tour en secondant Morgane depuis 2023.',
        ],
    ],

    'council' => [
        [
            'name' => 'César Chroscik',
            'title' => 'Responsable Promotions EPL/S 2010 & antérieures',
        ],
        [
            'name' => 'Julian Krummel',
            'title' => 'Responsable Promotion EPL/S 2011',
        ],
        [
            'name' => 'Jacques Preiss',
            'title' => 'Responsable Promotion EPL/S 2012',
        ],
        [
            'name' => 'Erwan Marlier',
            'title' => 'Responsable Promotion EPL/S 2013',
        ],
        [
            'name' => 'Timothée Barry',
            'title' => 'Responsable Promotion EPL/S 2014',
        ],
        [
            'name' => 'Théo Chamiot-Prieur',
            'title' => 'Responsable Promotion EPL/S 2015',
        ],
        [
            'name' => 'Thomas Izarn',
            'title' => 'Responsable Promotion EPL/S 2016',
        ],
        [
            'name' => 'Victor Agopian',
            'title' => 'Responsable Promotion EPL/S 2017',
        ],
        [
            'name' => 'Lilian Berquier',
            'title' => 'Responsable Promotion EPL/S 2018',
        ],
        [
            'name' => 'Louis Geig',
            'title' => 'Responsable Promotion EPL/S 2019',
        ],
        [
            'name' => 'Solal Lorcy',
            'title' => 'Responsable Promotion EPL/S 2020'
        ],
        [
            'name' => 'Marc Lesavre',
            'title' => 'Responsable Promotion EPL/S 2021'
        ],
        [
            'name' => 'Sébastien Vazelle',
            'title' => 'Responsable Promotion EPL/S 2022'
        ],
        [
            'name' => 'Florian Bartkowiak',
            'title' =>'Responsable Promotions EPL/U & EPL/P'
        ],
        [
            'name' => 'Zoé Kouvelas',
            'title' => 'Responsable Promotions Cursus Préparatoire ATPL',
        ],
        [
            'name' => 'Jérôme Walrave',
            'title' => 'Ancien Président 2002&#8209;2006',
        ],
        [
            'name' => 'Simon Spriet',
            'title' => 'Ancien Président 2006&#8209;2008',
        ],
        [
            'name' => 'Pierre Petaux',
            'title' => 'Ancien Président 2008&#8209;2010',
        ],
        [
            'name' => 'Timoté Dufour',
            'title' => 'Ancien Président 2010&#8209;2014',
        ],
        [
            'name' => 'Benjamin Payet',
            'title' => 'Ancien Président 2014&#8209;2016',
        ],
        [
            'name' => 'Damien Lacombe',
            'title' => 'Ancien Président 2016&#8209;2019',
        ],
        [
            'name' => 'Simon Louyot',
            'title' => 'Ancien Président 2019&#8209;2020',
        ],
        [
            'name' => 'Hugo Clarke-Wing',
            'title' => 'Ancien Président 2020&#8209;2023',
            'photo' => '/media/leadership/hugo-clarke-wing-face.jpg',
        ],
    ],

    'employers_showcase' => [
        // 'Aegean Airlines',
        'Aerosotravia',
        // 'Air Austral',
        // 'Air Caraibes',
        // 'Air Corsica',
        // 'Air France Hop',
        'Air France',
        'Air Macau',
        // 'Air Mauritius',
        // 'airBaltic',
        // 'AirCalin',
        // 'ASL Airlines France',
        // 'ASL Airlines Switzerland',
        // 'Astonfly',
        // 'Austrian Airlines',
        // 'Babcock International',
        // 'Blue Islands',
        // 'British Airways',
        'Cargolux',
        'Cathay Pacific',
        // 'Cebu Pacific',
        // 'Chalair Aviation',
        // 'CityJet',
        // 'Cretan Eagle Aviation',
        // 'DHL',
        'easyJet',
        'Emirates',
        // 'ENAC',
        // 'Etihad Airways',
        // 'Etihad Regional',
        // 'Flybe',
        // 'Flydubai',
        // 'Garuda Indonesia',
        // 'GlobalJet',
        // 'GlobeAir',
        // 'Hong Kong Airlines',
        // 'Intercaribbean Airways',
        // 'Jetstar',
        // 'La Compagnie',
        // 'LOT Polish Airlines',
        // 'Lufthansa Cityline',
        'Luxair',
        // 'LuxAviation',
        // 'Norwegian',
        // 'Oyonnair',
        // 'PixAir Survey',
        // 'PrivatAir',
        // 'Qantas',
        // 'Qatar Airways',
        // 'Ryanair',
        // 'St Barth Commuter',
        // 'St Barth Executive',
        // 'Susi Air',
        // 'Swiss',
        'Transavia',
        // 'TUI Fly',
        // 'VallJet',
        'VistaJet',
        // 'Volotea',
        // 'Vueling',
        // 'West Atlantic',
        // 'Wizz Air',
    ],

    'fallen_epls' => [
        [
            'name' => 'Guillaume G.',
            'promotion' => 'EPL 2006',
            'death' => 'Octobre 2011',
        ],
        [
            'name' => 'Pierre H.',
            'promotion' => 'EPL 2008',
            'death' => 'Juillet 2011',
        ],
        [
            'name' => 'Nicolas B.',
            'promotion' => 'EPL 2008',
            'death' => 'Décembre 2009',
        ],
        [
            'name' => 'Céline S.',
            'promotion' => 'EPL 2004',
            'death' => 'Aout 2004',
        ],
        [
            'name' => 'Jean M.',
            'promotion' => 'EPL A12',
            'death' => 'Juillet 2000',
        ],
    ],
];
